### ISSUE TITLE
"api" command not working with parameter or passed directly

### ISSUE THREAD

**Issue by goligo** [iotaledger/cli-app#18]
When starting the iota-cli and using the "api" command, I cannot pass the JSON as a parameter, but need to enter it separately:

```
iota (http://localhost:14265 ✓): api {"command": "getNodeInfo"}
Enter the command JSON: 

```
When trying to pass the "api" command directly as a command-line parameter to iota-cli, it does not execute, instead shows disconnection warning:

```
iota:/root@[23:28] # iota-cli api {"command":"getNodeInfo"} 
Running IOTA CLI v1.0.4

iota (http://localhost:14265 disconnected): 
It looks like you are not connected to an iota node.  Try "node".

iota (http://localhost:14265 disconnected): 

```

**Comment by TomRiedl** [comment]
Fixed with #28 

- `api` asks for command (the old behavior)
- `api {"command":"getNodeInfo"}` executes specified command
- `iota-cli api {"command":"getNodeInfo"}` could still print `not connected`. Do you have a node running on localhost:14265? If yes, then this should be addressed in a separate issue.
